# Generated by Django 4.2.30 on 2026-09-03 15:34

from django.db import migrations
import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0012_2_8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='capture_method',
            field=djstripe.fields.StripeEnumField(enum=djstripe.enums.CaptureMethod, max_length=15),
        ),
    ]
